# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ai-hiring-backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ai-hiring-backend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip-tools (for pip-compile)
      run: python -m pip install --upgrade pip pip-tools

    - name: Compile requirements.txt from requirements.in
      run: pip-compile requirements.in

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "API_USERNAME=${{ secrets.API_USERNAME }}" >> $GITHUB_ENV
        echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> $GITHUB_ENV


    - name: Set up Python module path
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # - name: Run Tests
    #   run: |
    #     pytest --cov=app --cov-report=term-missing tests/